version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  prometheus:
    build:
      context: ./prometheus/prometheus-docker
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus-docker/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api
    restart: unless-stopped